"""Added customers table

Revision ID: 611a2f8b9d9d
Revises: 5b6c27b45ed4
Create Date: 2023-09-07 16:46:14.722449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '611a2f8b9d9d'
down_revision = '5b6c27b45ed4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
