"""Added reviews table

Revision ID: f249bb18689c
Revises: 611a2f8b9d9d
Create Date: 2023-09-07 16:49:33.261195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f249bb18689c'
down_revision = '611a2f8b9d9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
